---
name: flo-test
description: Testing MLCs
repository: https://github.com/pulumi/pulumi-aws-apigateway
license: Apache-2.0
logoUrl: https://raw.githubusercontent.com/pulumi/pulumi-aws-apigateway/main/assets/logo.png
displayName: Florian Test
publisher: Pulumi
keywords:
  - pulumi
resources:
  flo-test:index:BucketComponent:
    isComponent: true
    properties:
      bucket: 
        "$ref": "/aws/v6.0.4/schema.json#/resources/aws:s3%2Fbucket:Bucket"
        description: |
          The underlying S3 Bucket resource.
    required:
      - bucket
    description: |
      The BucketComponent component offers a simple interface for creating an S3 bucket.
  flo-test:index:BucketObjectComponent:
    isComponent: true
    inputProperties:
      bucketComponent:
        "$ref": "#/resources/flo-test:index:BucketComponent"
        description: |
          The BucketComponent to use for the bucket object.
      key:
        type: string
        description: |
          The key of the object in the bucket.
      value:
        type: string
        description: |
          The value of the object in the bucket.
    requiredInputs:
      - bucketComponent
      - key
      - value
    properties:
      bucketObject: 
        "$ref": "/aws/v6.0.4/schema.json#/resources/aws:s3%2FbucketObject:BucketObject"
        description: |
          The underlying S3 BucketObject resource.
    required:
      - bucketObject
    description: |
      The BucketObjectComponent component offers a simple interface for creating an S3 bucket object.
language:
  csharp:
    namespaces:
      aws-apigateway: AwsApiGateway
    packageReferences:
      Pulumi: 3.*
      Pulumi.Aws: 6.*
    respectSchemaVersion: true
  go:
    importBasePath: github.com/pulumi/pulumi-aws-apigateway/sdk/v2/go/apigateway
    respectSchemaVersion: true
    generateExtraInputTypes: true
    internalModuleName: utilities
  nodejs:
    dependencies:
      "@pulumi/aws": "^6.0.0"
    respectSchemaVersion: true
  python:
    requires:
      pulumi-aws: ">=6.0.0,<7.0.0"
    respectSchemaVersion: true
    pyproject:
      enabled: true
  java:
    dependencies:
      "com.pulumi:aws": "6.5.0"
