// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

// Export members:
export { BucketComponentArgs } from "./bucketComponent";
export type BucketComponent = import("./bucketComponent").BucketComponent;
export const BucketComponent: typeof import("./bucketComponent").BucketComponent = null as any;
utilities.lazyLoad(exports, ["BucketComponent"], () => require("./bucketComponent"));

export { BucketObjectComponentArgs } from "./bucketObjectComponent";
export type BucketObjectComponent = import("./bucketObjectComponent").BucketObjectComponent;
export const BucketObjectComponent: typeof import("./bucketObjectComponent").BucketObjectComponent = null as any;
utilities.lazyLoad(exports, ["BucketObjectComponent"], () => require("./bucketObjectComponent"));

export { ProviderArgs } from "./provider";
export type Provider = import("./provider").Provider;
export const Provider: typeof import("./provider").Provider = null as any;
utilities.lazyLoad(exports, ["Provider"], () => require("./provider"));


const _module = {
    version: utilities.getVersion(),
    construct: (name: string, type: string, urn: string): pulumi.Resource => {
        switch (type) {
            case "flo-test:index:BucketComponent":
                return new BucketComponent(name, <any>undefined, { urn })
            case "flo-test:index:BucketObjectComponent":
                return new BucketObjectComponent(name, <any>undefined, { urn })
            default:
                throw new Error(`unknown resource type ${type}`);
        }
    },
};
pulumi.runtime.registerResourceModule("flo-test", "index", _module)
pulumi.runtime.registerResourcePackage("flo-test", {
    version: utilities.getVersion(),
    constructProvider: (name: string, type: string, urn: string): pulumi.ProviderResource => {
        if (type !== "pulumi:providers:flo-test") {
            throw new Error(`unknown provider type ${type}`);
        }
        return new Provider(name, <any>undefined, { urn });
    },
});
